#!/usr/bin/env python3
"""
Junmai AutoDev - Installer Creator
Version: 2.0

This script creates platform-specific installers.
"""

import os
import sys
import shutil
import subprocess
import platform
from pathlib import Path
import build_config

class InstallerCreator:
    """Creates platform-specific installers"""
    
    def __init__(self):
        self.platform = platform.system()
        self.dist_dir = build_config.BUILD_DIR / build_config.APP_NAME
        self.installer_dir = Path("installers")
        self.installer_dir.mkdir(parents=True, exist_ok=True)
    
    def create_windows_installer(self):
        """Create Windows installer using Inno Setup"""
        print("Creating Windows installer...")
        
        # Check if Inno Setup is installed
        inno_setup_path = Path(r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe")
        if not inno_setup_path.exists():
            print("  ✗ Inno Setup not found. Please install from: https://jrsoftware.org/isdl.php")
            return False
        
        # Create Inno Setup script
        iss_script = self._create_inno_setup_script()
        
        # Run Inno Setup
        try:
            result = subprocess.run([str(inno_setup_path), str(iss_script)],
                                   check=True, capture_output=True, text=True)
            print(result.stdout)
            print("  ✓ Windows installer created")
            return True
        except subprocess.CalledProcessError as e:
            print(f"  ✗ Failed to create installer:")
            print(e.stderr)
            return False
    
    def _create_inno_setup_script(self) -> Path:
        """Create Inno Setup script file"""
        script_content = f"""
; Junmai AutoDev Installer Script
; Generated by create_installer.py

#define MyAppName "{build_config.APP_NAME}"
#define MyAppVersion "{build_config.APP_VERSION}"
#define MyAppPublisher "{build_config.APP_AUTHOR}"
#define MyAppURL "https://github.com/junmai/autodev"
#define MyAppExeName "{build_config.APP_NAME}.exe"

[Setup]
AppId={{{{B8F3E9A1-7C4D-4B2E-9F1A-3D5C6E8A9B2C}}}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
AppPublisherURL={{#MyAppURL}}
AppSupportURL={{#MyAppURL}}
AppUpdatesURL={{#MyAppURL}}
DefaultDirName={{autopf}}\\{{#MyAppName}}
DefaultGroupName={{#MyAppName}}
AllowNoIcons=yes
LicenseFile=LICENSE
OutputDir=installers
OutputBaseFilename={{#MyAppName}}-{{#MyAppVersion}}-Setup
SetupIconFile=gui_qt\\resources\\icon.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\\Japanese.isl"

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{{cm:CreateQuickLaunchIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"; Flags: unchecked; OnlyBelowVersion: 6.1; Check: not IsAdminInstallMode

[Files]
Source: "dist\\{build_config.APP_NAME}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"
Name: "{{group}}\\{{cm:UninstallProgram,{{#MyAppName}}}}"; Filename: "{{uninstallexe}}"
Name: "{{autodesktop}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; Tasks: desktopicon
Name: "{{userappdata}}\\Microsoft\\Internet Explorer\\Quick Launch\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; Tasks: quicklaunchicon

[Run]
Filename: "{{app}}\\{{#MyAppExeName}}"; Description: "{{cm:LaunchProgram,{{#StringChange(MyAppName, '&', '&&')}}}}"; Flags: nowait postinstall skipifsilent

[Code]
function InitializeSetup(): Boolean;
var
  ResultCode: Integer;
begin
  // Check if Python is installed
  if not RegKeyExists(HKEY_LOCAL_MACHINE, 'SOFTWARE\\Python\\PythonCore\\3.11') and
     not RegKeyExists(HKEY_CURRENT_USER, 'SOFTWARE\\Python\\PythonCore\\3.11') then
  begin
    if MsgBox('Python 3.11 is required but not installed. Would you like to download it now?', 
              mbConfirmation, MB_YESNO) = IDYES then
    begin
      ShellExec('open', 'https://www.python.org/downloads/', '', '', SW_SHOW, ewNoWait, ResultCode);
    end;
    Result := False;
  end
  else
    Result := True;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
begin
  if CurStep = ssPostInstall then
  begin
    // Create data directories
    CreateDir(ExpandConstant('{{app}}\\data'));
    CreateDir(ExpandConstant('{{app}}\\logs'));
    CreateDir(ExpandConstant('{{app}}\\config'));
    
    // Initialize database
    Exec(ExpandConstant('{{app}}\\python.exe'), 
         ExpandConstant('{{app}}\\local_bridge\\init_database.py'),
         ExpandConstant('{{app}}'), SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;
end;
"""
        
        script_path = self.installer_dir / f"{build_config.APP_NAME}.iss"
        script_path.write_text(script_content)
        
        return script_path
    
    def create_macos_installer(self):
        """Create macOS installer (.dmg)"""
        print("Creating macOS installer...")
        
        app_bundle = self.dist_dir / f"{build_config.APP_NAME}.app"
        if not app_bundle.exists():
            print(f"  ✗ App bundle not found: {app_bundle}")
            return False
        
        dmg_name = f"{build_config.APP_NAME}-{build_config.APP_VERSION}.dmg"
        dmg_path = self.installer_dir / dmg_name
        
        # Remove existing DMG
        if dmg_path.exists():
            dmg_path.unlink()
        
        # Create DMG
        try:
            cmd = [
                'hdiutil', 'create',
                '-volname', build_config.APP_NAME,
                '-srcfolder', str(app_bundle),
                '-ov',
                '-format', 'UDZO',
                str(dmg_path)
            ]
            
            result = subprocess.run(cmd, check=True, capture_output=True, text=True)
            print(result.stdout)
            print(f"  ✓ macOS installer created: {dmg_path}")
            return True
            
        except subprocess.CalledProcessError as e:
            print(f"  ✗ Failed to create DMG:")
            print(e.stderr)
            return False
    
    def create_linux_installer(self):
        """Create Linux installer (.deb or .rpm)"""
        print("Creating Linux installer...")
        
        # For now, just create a tar.gz archive
        # In the future, could create .deb or .rpm packages
        
        archive_name = f"{build_config.APP_NAME}-{build_config.APP_VERSION}-linux"
        archive_path = self.installer_dir / archive_name
        
        try:
            shutil.make_archive(str(archive_path), 'gztar', 
                              build_config.BUILD_DIR, build_config.APP_NAME)
            
            final_archive = Path(f"{archive_path}.tar.gz")
            print(f"  ✓ Linux installer created: {final_archive}")
            return True
            
        except Exception as e:
            print(f"  ✗ Failed to create archive: {e}")
            return False
    
    def create_installer(self):
        """Create installer for current platform"""
        if not self.dist_dir.exists():
            print(f"✗ Distribution directory not found: {self.dist_dir}")
            print("  Please run build.py first")
            return False
        
        if self.platform == "Windows":
            return self.create_windows_installer()
        elif self.platform == "Darwin":
            return self.create_macos_installer()
        elif self.platform == "Linux":
            return self.create_linux_installer()
        else:
            print(f"✗ Unsupported platform: {self.platform}")
            return False


def main():
    """Main function"""
    print("=" * 60)
    print(f"Creating installer for {build_config.APP_NAME} v{build_config.APP_VERSION}")
    print(f"Platform: {platform.system()}")
    print("=" * 60)
    print()
    
    creator = InstallerCreator()
    
    if creator.create_installer():
        print()
        print("=" * 60)
        print("✓ Installer created successfully!")
        print("=" * 60)
        print(f"Output directory: {creator.installer_dir}")
        return 0
    else:
        print()
        print("=" * 60)
        print("✗ Failed to create installer")
        print("=" * 60)
        return 1


if __name__ == "__main__":
    sys.exit(main())
