; setup.nsi - NSIS Script for Junmai AutoDev
;
; This script defines the structure and behavior of the Windows installer
; using the Nullsoft Scriptable Install System (NSIS).

; --- Basic Application Info ---
!define APP_NAME "Junmai AutoDev"
!define APP_VERSION "2.0.0"
!define PUBLISHER "Junmai Systems"
!define WEBSITE "https://github.com/your-repo/junmai-autodev" ; Replace with actual URL
; Correctly define the executable name as generated by PyInstaller on Linux
!define EXE_NAME "JunmaiAutoDev"
!define SETUP_EXE_NAME "JunmaiAutoDev-v${APP_VERSION}-setup.exe"
!define OLLAMA_SETUP_EXE "OllamaSetup.exe"

; --- Installer Properties ---
; Use forward slashes for paths to be safe across environments
OutFile "/app/dist/${SETUP_EXE_NAME}"
InstallDir "$PROGRAMFILES\${APP_NAME}"
InstallDirRegKey HKLM "Software\${APP_NAME}" "Install_Dir"
RequestExecutionLevel admin ; Request admin rights for installation

; --- Modern UI ---
!include "MUI2.nsh"
!define MUI_ABORTWARNING
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"


; --- Installation Section ---
Section "Install"

  SetOutPath $INSTDIR

  ; Write the installation path to the registry
  WriteRegStr HKLM "Software\${APP_NAME}" "Install_Dir" "$INSTDIR"

  ; --- Main Application Executable ---
  ; Use the correct absolute path and the correct filename
  File "/app/dist/${EXE_NAME}"

  ; After copying the file, we rename it to have the .exe extension on the user's machine
  Rename "$INSTDIR\${EXE_NAME}" "$INSTDIR\${EXE_NAME}.exe"

  ; --- Bundled Ollama Installer ---
  SectionIn RO ; Required section
  SetOutPath $PLUGINSDIR
  File "dependencies/${OLLAMA_SETUP_EXE}"

  ; Execute the Ollama installer silently
  DetailPrint "Installing required AI Engine (Ollama)..."
  ; Use /S for silent install
  ExecWait '"$PLUGINSDIR\${OLLAMA_SETUP_EXE}" /S'

  SetOutPath $INSTDIR

  ; --- Shortcuts (pointing to the renamed .exe) ---
  CreateDirectory "$SMPROGRAMS\${APP_NAME}"
  CreateShortCut "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk" "$INSTDIR\${EXE_NAME}.exe"
  CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${EXE_NAME}.exe"

  ; --- Uninstaller ---
  WriteUninstaller "$INSTDIR\uninstall.exe"

SectionEnd


; --- Uninstallation Section ---
Section "Uninstall"

  ; Remove files (including the renamed .exe)
  Delete "$INSTDIR\${EXE_NAME}.exe"
  Delete "$INSTDIR\uninstall.exe"

  ; Remove shortcuts
  Delete "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk"
  Delete "$DESKTOP\${APP_NAME}.lnk"

  ; Remove directories
  RMDir "$SMPROGRAMS\${APP_NAME}"
  RMDir "$INSTDIR"

  ; Remove registry keys
  DeleteRegKey HKLM "Software\${APP_NAME}"

SectionEnd
